--INSERTANDO DATOS 

exec SPU_REGISTRAR_GRUPOS 1, 'A','T'
exec SPU_REGISTRAR_GRUPOS 1, 'B','M'
exec SPU_REGISTRAR_GRUPOS 1, 'C','T'
exec SPU_REGISTRAR_GRUPOS 1, 'D','M'
exec SPU_REGISTRAR_GRUPOS 1, 'E','T'

EXEC SPU_LISTAR_GRUPOS

EXEC SPU_EDITAR_GRUPOS 1, 1, 'A', 'M'
EXEC SPU_EDITAR_GRUPOS 3, 1, 'C', 'M'
EXEC SPU_EDITAR_GRUPOS 4, 1, 'D', 'T'